### ISSUE TITLE
The ability to transfer playerdata from one account to another

### ISSUE THREAD

**Issue by DorkOrc** [rx-modules/PlayerDB#11]
As discussed in [#help](https://discord.com/channels/400567034808762369/779982505704947733/801519905169080381), I would like to use this datapack on the Pandamium snapshot server which I help work on. Currently, operators must manually transfer players' scores from their old IGN to their new IGN when they change it, and on request transfer the scores to a new account altogether. That is usually up to 50 scores to manually transfer, so the ability to automate this with your datapack would be great; however, there currently isn't a nice way to change the UUID of a player's entry while keeping the same `uid`, as changing the UUID messes up the UUIDdb. This makes transferring data across different accounts not easy.
The server has had thousands of players, and currently has hundreds of active players, so it would be greatly appreciated if you could implement this feature, as you know how to navigate the pack best.

**Comment by RitikShah** [comment]
This would involve creating an `admin` function that keeps some things in mind:
UUID of the old account, UUID of the new account, uid to keep, uid to ditch.

Situation:
- Player A has uid 1, UUID a-a-a-a-a
- Player A changes account to Player DB, now has uid 2, UUID b-b-b-b-b
- Player B wants data from old Player A

Solution:
- Find Player A UUIDdb entry and cache UUID and replace with Player B UUID
- Sore original (Player A) uid w/ Player B's uid
- Give Player A the Player B uid
- Store Player A's UUID in PlayerB UUID's spot
- Recalculate all of rx.uuid0 -> rx.uuid3

Issues:
- Players may or may not be online. Resetting scores must be done manually as no selector can select an offline player
- The state of the db must always be valid
- Input should be consider carefully to not collide with API calls

This is just reference when I tackle this

**Comment by RitikShah** [comment]
This has been added! Documentation coming soon
