### ISSUE TITLE
Players' rx.uid score getting set to 0 and/or reset

### ISSUE THREAD

**Issue by GrifterMage** [rx-modules/PlayerDB#15]
Been having some issues with playerDB, and I can't seem to figure out what the heck is going on. I've had:
--Players getting their rx.uid score set to 0.
--Players getting their rx.uid score reset.
--The specific-UUID armor stand used in impl/get_name not being removed (despite the patch to #13)--armor stand doesn't get teleported at all.

Our server hasn't crashed, but does perform a scheduled reset every two hours.

**Comment by RitikShah** [comment]
I think this has been resolved in the latest commit (eeceb78). I'll close this, but we can open it in the future if need be!
