### ISSUE TITLE
UUID Select only searches the first bit of UUID[0]

### ISSUE THREAD

**Issue by GrifterMage** [rx-modules/PlayerDB#16]
Currently, UUID Select will always quit searching after checking bit 0, because if there's one and only one entry that matches the first bit, the system assumes all the remaining bits match.

As a result, the UUID database will never create multiple entries with the same bit 0, so it will continue never checking the later bits.

**Comment by GrifterMage** [comment]
Created fix for this: #17

**Comment by RitikShah** [comment]
Fixed in latest commit: eeceb78
