### ISSUE TITLE
Missing player amounts

### ISSUE THREAD

**Issue by Command-Master** [rx-modules/PlayerDB#7]
In the lag debug results you didn't write how many players are in the storage and are currently online, which makes comparing this to other methods harder. Could you please add how many players are stored and how many are online?

**Comment by RitikShah** [comment]
Yea, this is true. I would like to do a more in-depth analysis. I ran the function `rx.playerdb:test/summon_50_players` which uses carpet mod to summon 49 fake players (and then I'm the 50th). Then, in each player's storage for EntityDB, PlayerDB, and their EnderChest (an item w/ stick), I store 5 copies of an inventory full of diamond swords for some fake data.

Then, I run my get and get/saves on a `execute as @a` for this test. In the future, I'd like to test a bit more depth, but if you'd like, feel free to run your own tests and I can add them to the README.md (or make a PR)!

**Comment by RitikShah** [comment]
I've updated the lag results recently and in my upcoming 0.8 update, I'll try to make a better post. Do you have any suggestions on how to gauge performance and help compare w/ other methods?

**Comment by RitikShah** [comment]
Closing w/ lack of response. You can reopen later
